version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: mdillon/postgis:9.6-alpine
    restart: always
    # environment:
    #   POSTGRES_DB: superset
    #   POSTGRES_PASSWORD: superset
    #   POSTGRES_USER: superset
    environment:
      POSTGRES_DB: postgres
      POSTGRES_SUPERSET_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - mypgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    entrypoint: >
      ash -c "wget -N -P /docker-entrypoint-initdb.d https://raw.githubusercontent.com/lejedi76/dvf-superset/test_import_superset_conf/00_initdb-postgis.sh  &&
              wget -N -P /docker-entrypoint-initdb.d https://raw.githubusercontent.com/lejedi76/dvf-superset/test_import_superset_conf/superset.sql.gz &&
              /docker-entrypoint.sh"
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      POSTGRES_SUPERSET_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    entrypoint: >
    bash -c "wget https://raw.githubusercontent.com/lejedi76/dvf-superset/test_import_superset_conf/superset_config.py &&
             gunicorn supperset:app.py"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: superset@me.org
      PGADMIN_DEFAULT_PASSWORD: superset
    ports:
      - "10080:80"
    volumes:
      - mypgadmindata:/var/lib/pgadmin
volumes:
  mypgdata:
  redis:
  mypgadmindata:
