version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: mdillon/postgis:9.6-alpine
    restart: always
    # environment:
    #   POSTGRES_DB: superset
    #   POSTGRES_PASSWORD: superset
    #   POSTGRES_USER: superset
    env_file:
      - .env
    volumes:
      - mypgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    env_file:
      - .env
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "10080:80"
    volumes:
      - mypgadmindata:/var/lib/pgadmin
volumes:
  mypgdata:
  redis:
  mypgadmindata:
